/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GamesRouteImport } from './routes/games'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaySlugRouteImport } from './routes/play.$slug'
import { Route as ApiWpoSlugRouteImport } from './routes/api/wpo.$slug'
import { Route as ApiWpSlugRouteImport } from './routes/api/wp.$slug'
import { Route as ApiPlayFileRouteImport } from './routes/api/play.$file'
import { Route as ApiEmuSlugRouteImport } from './routes/api/emu.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySlugRoute = PlaySlugRouteImport.update({
  id: '/play/$slug',
  path: '/play/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWpoSlugRoute = ApiWpoSlugRouteImport.update({
  id: '/api/wpo/$slug',
  path: '/api/wpo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWpSlugRoute = ApiWpSlugRouteImport.update({
  id: '/api/wp/$slug',
  path: '/api/wp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayFileRoute = ApiPlayFileRouteImport.update({
  id: '/api/play/$file',
  path: '/api/play/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmuSlugRoute = ApiEmuSlugRouteImport.update({
  id: '/api/emu/$slug',
  path: '/api/emu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/games': typeof GamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/play/$slug': typeof PlaySlugRoute
  '/api/emu/$slug': typeof ApiEmuSlugRoute
  '/api/play/$file': typeof ApiPlayFileRoute
  '/api/wp/$slug': typeof ApiWpSlugRoute
  '/api/wpo/$slug': typeof ApiWpoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/games': typeof GamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/play/$slug': typeof PlaySlugRoute
  '/api/emu/$slug': typeof ApiEmuSlugRoute
  '/api/play/$file': typeof ApiPlayFileRoute
  '/api/wp/$slug': typeof ApiWpSlugRoute
  '/api/wpo/$slug': typeof ApiWpoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/games': typeof GamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/play/$slug': typeof PlaySlugRoute
  '/api/emu/$slug': typeof ApiEmuSlugRoute
  '/api/play/$file': typeof ApiPlayFileRoute
  '/api/wp/$slug': typeof ApiWpSlugRoute
  '/api/wpo/$slug': typeof ApiWpoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/games'
    | '/sitemap.xml'
    | '/play/$slug'
    | '/api/emu/$slug'
    | '/api/play/$file'
    | '/api/wp/$slug'
    | '/api/wpo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/games'
    | '/sitemap.xml'
    | '/play/$slug'
    | '/api/emu/$slug'
    | '/api/play/$file'
    | '/api/wp/$slug'
    | '/api/wpo/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/games'
    | '/sitemap.xml'
    | '/play/$slug'
    | '/api/emu/$slug'
    | '/api/play/$file'
    | '/api/wp/$slug'
    | '/api/wpo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GamesRoute: typeof GamesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PlaySlugRoute: typeof PlaySlugRoute
  ApiEmuSlugRoute: typeof ApiEmuSlugRoute
  ApiPlayFileRoute: typeof ApiPlayFileRoute
  ApiWpSlugRoute: typeof ApiWpSlugRoute
  ApiWpoSlugRoute: typeof ApiWpoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$slug': {
      id: '/play/$slug'
      path: '/play/$slug'
      fullPath: '/play/$slug'
      preLoaderRoute: typeof PlaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wpo/$slug': {
      id: '/api/wpo/$slug'
      path: '/api/wpo/$slug'
      fullPath: '/api/wpo/$slug'
      preLoaderRoute: typeof ApiWpoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wp/$slug': {
      id: '/api/wp/$slug'
      path: '/api/wp/$slug'
      fullPath: '/api/wp/$slug'
      preLoaderRoute: typeof ApiWpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/play/$file': {
      id: '/api/play/$file'
      path: '/api/play/$file'
      fullPath: '/api/play/$file'
      preLoaderRoute: typeof ApiPlayFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/emu/$slug': {
      id: '/api/emu/$slug'
      path: '/api/emu/$slug'
      fullPath: '/api/emu/$slug'
      preLoaderRoute: typeof ApiEmuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GamesRoute: GamesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PlaySlugRoute: PlaySlugRoute,
  ApiEmuSlugRoute: ApiEmuSlugRoute,
  ApiPlayFileRoute: ApiPlayFileRoute,
  ApiWpSlugRoute: ApiWpSlugRoute,
  ApiWpoSlugRoute: ApiWpoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
